import Head from 'next/head'
import { Button, EditIcon } from '@/components/mui'
import Layout from '@/components/Layout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Shop - Fullstack app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Contact Page</h1>
        <Button variant="contained"> <EditIcon/>Button</Button>
      </Layout>
    </>
  )
}
